@server=http://localhost:4004
@username=alice
@password=


### Books
# @name Books_GET
GET {{server}}/odata/v4/catalog/Books
Authorization: Basic {{username}}:{{password}}


### Books
# @name Books_POST
POST {{server}}/odata/v4/catalog/Books
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": 102581,
  "title": "title-102581",
  "author": "author-102581"
}


### Books
# @name Books_PATCH
PATCH {{server}}/odata/v4/catalog/Books/102581
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": 102581,
  "title": "title-102581",
  "author": "author-102581"
}


### Books
# @name Books_DELETE
DELETE {{server}}/odata/v4/catalog/Books/102581
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}
